# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Emily Blog
tagline:          'A blog for Emily'
description:      
url:              https://emilyb09.github.io/emily-blog/
baseurl:          https://emilyb09.github.io/emily-blog/

author:
  name:           'Emily Bowman'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
